# Generated by Django 5.1 on 2024-08-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiences",
            name="end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="experiences",
            name="start_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
