# Generated by Django 5.1 on 2024-08-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_experiences_end_date_experiences_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencies",
            name="additional_description",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="experiences",
            name="description",
            field=models.TextField(max_length=900),
        ),
    ]
