# Generated by Django 5.1 on 2024-08-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_competencies_additional_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencies",
            name="additional_description",
            field=models.TextField(default=None, max_length=400),
        ),
    ]
