# Generated by Django 5.1 on 2024-08-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_competencies_additional_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencies",
            name="additional_description",
            field=models.TextField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
