# Generated by Django 5.1 on 2024-09-12 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_competencies_additional_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Experiences",
            new_name="Education",
        ),
    ]
