# Generated by Django 5.1 on 2024-09-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_rename_experiences_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
