# Generated by Django 5.1 on 2024-09-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_education_end_date_alter_education_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "additional_description",
                    models.TextField(
                        blank=True, default=None, max_length=400, null=True
                    ),
                ),
            ],
        ),
    ]
